---
- name: Install Packages
  hosts: localhost
  tasks:
    - name: Install vim, tree, wget, curl
      yum:
        name:
          - vim
          - tree
          - wget
          - curl
        state: latest